# Generated by Django 4.2.16 on 2025-05-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcover',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='bookcover',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='bookcover',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='bookcover',
            name='image_path',
            field=models.CharField(blank=True, help_text='Путь к изображению в папке static/images', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcover_set', to='bookstoreapp.book'),
        ),
    ]
